# 파일 경로: .github/workflows/deploy.yml

name: Deploy to Server

on:
  push:
    branches:
      - main # main 브랜치에 push 이벤트가 발생했을 때 워크플로우를 실행합니다.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }} # 원격 서버 IP (GitHub Secrets에 저장)
          username: ${{ secrets.SERVER_USERNAME }} # 서버 사용자명 (GitHub Secrets에 저장)
          key: ${{ secrets.SSH_PRIVATE_KEY }} # SSH 프라이빗 키 (GitHub Secrets에 저장)
          source: "."
          target: "/home/asapsoft/public_html/subdivision"